name: Instant Merge Konflux PRs

on:
  pull_request:
    types:
      - opened
    paths:
      - config/overlays/odh/params.env

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  instant-merge:
    runs-on: ubuntu-latest
    steps:
      - name: instant-merge
        if: ${{ github.event.sender.login == 'red-hat-konflux' && startsWith(github.event.pull_request.title, 'Update kserve-') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}
